#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

---
kind: Template
apiVersion: v1
metadata:
  name: che-logs-propagator
  annotations:
    description: Che logs propagator
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: che-logs-propagator
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: che-logs-propagator
- apiVersion: v1
  kind: Route
  metadata:
    name: che-logs-propagator
  spec:
    to:
      kind: Service
      name: che-logs-propagator
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: che-logs-propagator
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: che-logs-propagator
    strategy:
      type: ${STRATEGY}
    template:
      metadata:
        labels:
          app: che-logs-propagator
      spec:
        containers:
        - env:
          - name: CHE_API
            value: "${CHE_API}"
          - name: CHE_DEBUG_SERVER
            value: "false"
          - name: CHE_LOGS_SENTRY_LEVEL
            value: "WARN"
          - name: SENTRY_DSN
            value: ""
          - name: SENTRY_STACKTRACE_APP_PACKAGES
            value: "com.redhat,org.eclipse.che"
          - name: SENTRY_ENVIRONMENT
            value: "dev"
          - name: SENTRY_RELEASE
            value: "dev"
          - name: CHE_LOG_LEVEL
            value: "INFO"
          - name: CHE_KEYCLOAK_AUTH__SERVER__URL
            value: "${CHE_KEYCLOAK_AUTH__SERVER__URL}"
          - name: JAVA_OPTS
            value: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
              -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
              -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
              -Xms20m "
          image: ${IMAGE}:${IMAGE_VERSION}
          imagePullPolicy: "${PULL_POLICY}"
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            failureThreshold: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 5
            failureThreshold: 5
          name: che
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8000
            name: http-debug
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
        restartPolicy: Always
        terminationGracePeriodSeconds: 360
    triggers:
    - type: ConfigChange

parameters:
- name: IMAGE_VERSION
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: nightly
- name: CHE_API
  displayName: Eclipse Che API URL
  description: Eclipse Che API (including path to API)
- name: IMAGE
  displayName: Eclipse Che logs propagator server image
  description: Che logs propagator server Docker image. Defaults to eclipse/che-logs
  value: eclipse/che-logs
- name: CHE_KEYCLOAK_AUTH__SERVER__URL
  displayName: Identity provider URL
  description: URL of a remote identity provider. Defaults to Keycloak bundled with Che multi user
- name: STRATEGY
  displayName: Update Strategy
  description: Che server update strategy. Defaults to Recreate. Use Rolling only if Che deployment does not use PVC
  value: 'Recreate'
- name: PULL_POLICY
  displayName: Che server image pull policy
  description: Always pull by default. Can be IfNotPresent
  value: 'Always'
labels:
  app: che-logs-propagator
  template: che-logs-propagator
